### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by KristofferC** [JuliaInv/KrylovMethods.jl#21]
It seems this package passes all tests on 1.0, 1.1 so perhaps a new release is on order since the current one does not support 0.7+.

**Comment by lruthotto** [comment]
definitely. need to look into how to do this correctly though. last time was a little rough :)

**Comment by KristofferC** [comment]
Easiest way is to install https://github.com/attobot/attobot and then just tag a new release from the GitHub release section.

**Comment by lruthotto** [comment]
Thanks a lot Kristoffer. I've just done so. Hope this is fixed now.

**Comment by KristofferC** [comment]
Almost fixed :).

As can be seen in the METADATA Travis run (https://travis-ci.org/JuliaLang/METADATA.jl/jobs/495228426#L488) it errors because julia 0.5 is umaintained so no new releases are being accepted for it. You can bump to `julia 0.7` in REQUIRE, remove the new release from Github and retag a new release to update the PR.

**Comment by lruthotto** [comment]
Thanks again. I did exactly that. Hope we're good now.

**Comment by lruthotto** [comment]
@JuliaRegistrator register()

**Comment by lruthotto** [comment]
@JuliaRegistrator register()

**Comment by lruthotto** [comment]
@JuliaRegistrator register()

**Comment by lruthotto** [comment]
@JuliaRegistrator register()
